import { Router } from "express";
import { adFormatsRouter, adminAdFormatsRouter } from "./modules/ad-formats/ad-format.routes.js";
import { adminAdsRouter, adsRouter } from "./modules/ads/ads.routes.js";
import { adminFaqsRouter, faqsRouter } from "./modules/faqs/faqs.routes.js";
import { adminLeadsRouter, advertisingRouter, contactRouter, dataLicenceRouter, demoRequestsRouter } from "./modules/leads/leads.routes.js";
import { adminNewsRouter, newsRouter } from "./modules/news/news.routes.js";
import { adminNewsletterRouter, newsletterRouter } from "./modules/newsletter/newsletter.routes.js";
import { adminPricingRouter, pricingRouter } from "./modules/pricing/pricing.routes.js";
import { adminAirportsRouter, airportsRouter } from "./modules/airports/airports.routes.js";
import { adminAuthRouter } from "./modules/admin-auth/admin-auth.routes.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { adminCategoriesRouter, categoriesRouter } from "./modules/categories/category.routes.js";
import { adminBillingRouter, billingRouter } from "./modules/billing/billing.routes.js";
import { adminEnquiriesRouter, enquiriesRouter, myEnquiriesRouter, providerEnquiriesRouter } from "./modules/enquiries/enquiry.routes.js";
import { favoritesRouter } from "./modules/favorites/favorites.routes.js";
import { adminProvidersRouter, myListingRouter, providersRouter } from "./modules/providers/providers.routes.js";
import { reportsRouter } from "./modules/reports/reports.routes.js";
import { adminReviewsRouter, myReviewsRouter, providerReviewsRouter } from "./modules/reviews/review.routes.js";
import { filesRouter, myUploadsRouter, uploadsRouter } from "./modules/uploads/uploads.routes.js";
import { adminUsersRouter } from "./modules/users/admin-users.routes.js";

/** Mounts every feature module under /api/v1. */
export function apiRoutes(): Router {
  const router = Router();
  router.use("/auth", authRouter);
  router.use("/categories", categoriesRouter);
  router.use("/airports", airportsRouter);
  router.use("/providers", providersRouter);
  router.use("/providers", providerReviewsRouter);
  router.use("/providers", providerEnquiriesRouter);
  router.use("/enquiries", enquiriesRouter);
  router.use("/news", newsRouter);
  router.use("/faqs", faqsRouter);
  router.use("/ads", adsRouter);
  router.use("/pricing", pricingRouter);
  router.use("/contact", contactRouter);
  router.use("/demo-requests", demoRequestsRouter);
  router.use("/data-licence", dataLicenceRouter);
  router.use("/advertising/formats", adFormatsRouter);
  router.use("/advertising", advertisingRouter);
  router.use("/newsletter", newsletterRouter);
  router.use("/me/listing", myListingRouter);
  router.use("/me/favorites", favoritesRouter);
  router.use("/me/reviews", myReviewsRouter);
  router.use("/me/enquiries", myEnquiriesRouter);
  router.use("/uploads", uploadsRouter);
  router.use("/files", filesRouter);
  router.use("/me/uploads", myUploadsRouter);
  router.use("/billing", billingRouter);
  router.use("/admin/auth", adminAuthRouter);
  // Staff upload through their own (admin-scoped) session.
  router.use("/admin/uploads", uploadsRouter);
  router.use("/admin/users", adminUsersRouter);
  router.use("/admin/airports", adminAirportsRouter);
  router.use("/admin/providers", adminProvidersRouter);
  router.use("/admin/categories", adminCategoriesRouter);
  router.use("/admin/billing", adminBillingRouter);
  router.use("/admin/reports", reportsRouter);
  router.use("/admin/reviews", adminReviewsRouter);
  router.use("/admin/news", adminNewsRouter);
  router.use("/admin/faqs", adminFaqsRouter);
  router.use("/admin/ads", adminAdsRouter);
  router.use("/admin/ad-formats", adminAdFormatsRouter);
  router.use("/admin/pricing", adminPricingRouter);
  router.use("/admin/leads", adminLeadsRouter);
  router.use("/admin/newsletter", adminNewsletterRouter);
  router.use("/admin/enquiries", adminEnquiriesRouter);
  return router;
}
